import { figmaAssets } from '@/assets/figma';
import type {
  ChartSeries,
  DashboardData,
  Discovery,
  DiscoveryDetail,
  DiscoveriesListData,
  NotificationItem,
  ReviewerProfile,
  UserProfile,
} from '@/types/discovery';

export const stubUser: UserProfile = {
  name: 'Иванов С.\u2009Р.',
  line: 'L1',
  initials: 'С\u2009И',
  location: 'Буровая Осташковичи 123 • Бригада 2',
};

export const stubReviewerL3: ReviewerProfile = {
  name: 'Константинопольская О.\u2009В.',
  initials: 'О\u2009К',
  role: 'Ответственный за ОТиПБ',
  line: 'L3',
};

const thumb = figmaAssets.tableThumb;

const discoveryA79096: DiscoveryDetail = {
  id: 'A79096',
  title: 'Обнаружение A79096 • Нет каски',
  shortTitle: 'Нет каски',
  fullTitle:
    'Обнаружение A79096: Использование автоматического бурового ключа с\u00a0незакрытой дверкой (ZQ-203/100) на\u00a0столе ротора при\u00a0креплении бурильного инструмента',
  violationType: 'Нет каски',
  suspectedViolation: 'Нет каски',
  violationCategory: 'Средства индивидуальной защиты',
  objectName: 'Осташковичи 123',
  master: 'Иванов С.\u2009Р.',
  brigade: '№\u20092',
  zone: 'Цех №1',
  detectionZone: 'Зона №1',
  cameraId: 'CAM928',
  cameraName: 'Камера у\u00a0входа',
  detectedAt: '13 марта 2027 10:53:55',
  detectedAtRelative: '3 дня назад',
  receivedAt: '15 марта 2027 12:02',
  receivedAtRelative: '2 дня назад',
  deadlineAt: 'до 16 марта 2027 12:02',
  deadlineTimer: '🔥 59:22',
  status: 'pending',
  statusLabel: 'Ожидает обработки',
  statusKind: 'pending',
  violators: 'Константинопольский\u00a0С.\u2009Р, Романов\u00a0И.\u2009Р.',
  line: 'L1',
  locationLine: 'Цех №1 • CAM928 • Камера у\u00a0входа',
  thumbnailUrl: thumb,
  videoTimestamp: '02/01/2025 02:52:35',
  keyFrameRecordedAt: '2027-03-13T07:53:35.000Z',
  mainFrameId: 'A79096-f030',
  evaluationQuestion: 'Как вы оцениваете это обнаружение?',
  currentReviewer: stubReviewerL3,
  statusHistory: [
    {
      id: '1',
      line: 'L1',
      userName: 'Иванов С.\u2009Р.',
      userInitials: 'С\u2009И',
      role: 'Мастер буровой • Бригада №\u20092',
      timestamp: '14 марта 2027 16:45',
      status: 'Нарушение',
      statusKind: 'violation',
      violators: 'Константинопольский\u00a0С.\u2009Р, Романов\u00a0И.\u2009Р.',
      comment: 'Цех плохо освещён, сложно\u00a0определить, что происходит в\u00a0кадре',
    },
    {
      id: '2',
      line: 'L2',
      userName: 'Захаров-Добровольский А.\u2009В.',
      userInitials: 'А\u2009З',
      role: 'Заместитель начальника ЦИТС',
      timestamp: '15 марта 2027 12:02',
      status: 'Ошибка ИИ',
      statusKind: 'ai_error',
      comment: 'Цех действительно плохо освещён, скорее всего сотрудник не\u00a0нарушил',
    },
  ],
};

const moreDiscoveries: Discovery[] = [
  {
    id: 'A79099',
    title: 'Обнаружение A79099 • Нет каски',
    shortTitle: 'Нет каски',
    fullTitle: 'Обнаружение A79099: Работа без каски в производственной зоне',
    violationType: 'Нет каски',
    suspectedViolation: 'Нет каски',
    violationCategory: 'Средства индивидуальной защиты',
    objectName: 'Осташковичи 123',
    master: 'Иванов С.\u2009Р.',
    brigade: '№\u20092',
    zone: 'Цех №1',
    detectionZone: 'Зона №1',
    cameraId: 'CAM202',
    cameraName: 'Камера у\u00a0стола',
    detectedAt: '10.03.2027 14:52:35',
    detectedAtRelative: 'Сейчас 🔥',
    receivedAt: '10.03.2027 14:55',
    receivedAtRelative: 'Сейчас 🔥',
    deadlineAt: 'до 11.03.2027 14:55',
    deadlineTimer: '🔥 10:22',
    deadlineSub: 'Остался 1 день',
    status: 'pending',
    statusLabel: 'Ожидает обработки',
    statusKind: 'pending',
    statusSub: 'Остался 1 день',
    violators: 'Семёнов А.\u2009В. • 12345678',
    line: 'L1',
    thumbnailUrl: thumb,
  },
  {
    id: 'A79096',
    title: discoveryA79096.title,
    shortTitle: 'Нет каски',
    fullTitle: discoveryA79096.fullTitle,
    violationType: 'Нет каски',
    suspectedViolation: 'Использование автоматического бурового ключа…',
    violationCategory: 'Технические операции',
    objectName: 'Осташковичи 123',
    master: 'Иванов С.\u2009Р.',
    brigade: '№\u20092',
    zone: 'Цех №1',
    detectionZone: 'Зона №1',
    cameraId: 'CAM005',
    cameraName: 'Камера у\u00a0входа',
    detectedAt: '09.03.2027 13:04:00',
    detectedAtRelative: '4 минуты назад',
    receivedAt: '09.03.2027 13:05',
    receivedAtRelative: '4 минуты назад',
    deadlineAt: 'до 10.03.2027 13:05',
    deadlineTimer: '🔥 45:00',
    status: 'pending',
    statusLabel: 'Ожидает обработки',
    statusKind: 'pending',
    statusSub: 'Осталось 2 часа',
    violators: '—',
    line: 'L1',
    thumbnailUrl: thumb,
  },
  {
    id: 'A79097',
    title: 'Обнаружение A79097 • Нет перчаток',
    shortTitle: 'Нет перчаток',
    fullTitle: 'Обнаружение A79097: Отсутствие защитных перчаток',
    violationType: 'Нет перчаток',
    suspectedViolation: 'Нет перчаток',
    violationCategory: 'Средства индивидуальной защиты',
    objectName: 'Осташковичи 123',
    master: 'Иванов С.\u2009Р.',
    brigade: '№\u20092',
    zone: 'Цех №1',
    detectionZone: 'Зона №2',
    cameraId: 'CAM005',
    cameraName: 'Камера у\u00a0ротора',
    detectedAt: '08.03.2027 08:15:00',
    detectedAtRelative: 'Вчера',
    receivedAt: '08.03.2027 08:20',
    deadlineAt: 'до 09.03.2027 08:20',
    deadlineTimer: '🔥 12:45',
    status: 'violation',
    statusLabel: 'Нарушение',
    statusKind: 'violation',
    statusSub: '08.03.2027 10:15',
    violators: 'Петров\u00a0А.\u2009В.',
    line: 'L1',
    thumbnailUrl: thumb,
  },
  {
    id: 'B79095',
    title: 'Обнаружение B79095 • Запрещённая зона',
    shortTitle: 'Запрещённая зона',
    fullTitle:
      'Обнаружение B79095: Нахождение на столе ротора при работе телевой системы при её подъёме',
    violationType: 'Запрещённая зона',
    suspectedViolation: 'Нахождение на столе ротора при работе телевой системы при её подъёме',
    violationCategory: 'Запрещённые зоны',
    objectName: 'Осташковичи 123',
    master: 'Иванов С.\u2009Р.',
    brigade: '№\u20092',
    zone: 'Цех №1',
    detectionZone: 'Зона №1',
    cameraId: 'CAM202',
    cameraName: 'Камера у\u00a0стола',
    detectedAt: '10.03.2027 13:58:35',
    detectedAtRelative: '54 минуты назад',
    receivedAt: '10.03.2027 14:00',
    receivedAtRelative: '52 минуты назад',
    deadlineAt: 'до 11.03.2027 14:00',
    deadlineTimer: '🔥 28:10',
    status: 'pending',
    statusLabel: 'Ожидает обработки',
    statusKind: 'pending',
    violators: '—',
    line: 'L1',
    thumbnailUrl: thumb,
  },
  {
    id: 'A79098',
    title: 'Обнаружение A79098 • Нарушение зоны',
    shortTitle: 'Нарушение зоны',
    fullTitle: 'Обнаружение A79098: Пересечение опасной зоны',
    violationType: 'Нарушение зоны',
    suspectedViolation: 'Работа без удерживающих металлических крючков',
    violationCategory: 'Запрещённые зоны',
    objectName: 'Осташковичи 123',
    master: 'Иванов С.\u2009Р.',
    brigade: '№\u20092',
    zone: 'Цех №2',
    detectionZone: 'Зона №3',
    cameraId: 'CAM012',
    cameraName: 'Камера у\u00a0склада',
    detectedAt: '07.03.2027 11:30:00',
    detectedAtRelative: '2 дня назад',
    receivedAt: '07.03.2027 11:35',
    deadlineAt: 'до 08.03.2027 11:35',
    deadlineTimer: '🔥 28:10',
    status: 'ai_error',
    statusLabel: 'Ошибка ИИ',
    statusKind: 'ai_error',
    statusSub: '07.03.2027 14:00',
    violators: '—',
    line: 'L1',
    thumbnailUrl: thumb,
  },
];

export const stubDiscoveries: Discovery[] = [discoveryA79096, ...moreDiscoveries.filter((d) => d.id !== 'A79096')];

export const stubDashboard: DashboardData = {
  problemsCount: 3,
  events: [
    { id: '1', time: '10:34', message: 'Восстановлена связь с камерой CAM005', type: 'success' },
    { id: '2', time: '10:23', message: 'Потеряна связь с сервером', type: 'error' },
    { id: '3', time: '10:22', message: 'Потеряна связь с камерой CAM005', type: 'error' },
    { id: '4', time: '10:11', message: 'Потеряна связь с камерой CAM005', type: 'error' },
  ],
  unprocessedCount: 10,
  expiringCount: 12,
  unprocessed: stubDiscoveries.filter((d) => d.statusKind === 'pending').slice(0, 4),
  expiring: stubDiscoveries.filter((d) => d.status === 'expiring' || d.deadlineSub).slice(0, 4),
};

export function getDiscoveriesList(tab: 'all' | 'pending' | 'expiring'): DiscoveriesListData {
  let items = [...stubDiscoveries];
  if (tab === 'pending') items = items.filter((d) => d.statusKind === 'pending');
  if (tab === 'expiring') items = items.filter((d) => d.deadlineSub || d.status === 'expiring');
  return {
    total: 122,
    filtered: items.length,
    pendingCount: 4,
    expiringCount: 2,
    items,
  };
}

export function getDiscoveryDetail(id: string): DiscoveryDetail | null {
  if (id === 'A79096') return discoveryA79096;
  const found = stubDiscoveries.find((d) => d.id === id);
  if (!found) return null;
  return {
    ...found,
    fullTitle: found.fullTitle ?? found.title,
    statusHistory: [],
    evaluationQuestion: 'Как вы оцениваете это обнаружение?',
    currentReviewer: stubReviewerL3,
    videoTimestamp: '02/01/2025 02:52:35',
    keyFrameRecordedAt: '2027-03-13T07:53:35.000Z',
    mainFrameId: `${found.id}-f030`,
  };
}

export const stubNotifications: NotificationItem[] = [
  {
    id: 'n1',
    title: 'Обнаружение A79096 • Нет каски',
    subtitle: 'Есть 3 проблемы',
    time: '12:02',
    type: 'discovery',
    read: false,
    discoveryId: 'A79096',
  },
  {
    id: 'n2',
    title: 'Обнаружение A79097 • Нет перчаток',
    time: '08:20',
    type: 'deadline',
    read: false,
    discoveryId: 'A79097',
  },
  {
    id: 'n3',
    title: 'Потеряна связь с камерой CAM005',
    time: '10:22',
    type: 'system',
    read: true,
  },
  {
    id: 'n4',
    title: 'Восстановлена связь с камерой CAM005',
    time: '10:34',
    type: 'system',
    read: true,
  },
  {
    id: 'n5',
    title: 'Обнаружение A79098 • Нарушение зоны',
    time: '11:35',
    type: 'discovery',
    read: false,
    discoveryId: 'A79098',
  },
];

export const stubChartData: ChartSeries[] = [
  { label: 'Янв', violations: 12, aiErrors: 4, overdue: 2 },
  { label: 'Фев', violations: 18, aiErrors: 6, overdue: 3 },
  { label: 'Мар', violations: 15, aiErrors: 8, overdue: 5 },
  { label: 'Апр', violations: 22, aiErrors: 5, overdue: 4 },
  { label: 'Май', violations: 19, aiErrors: 7, overdue: 6 },
  { label: 'Июн', violations: 14, aiErrors: 3, overdue: 2 },
];
